import Head from 'next/head'
import Hero from '../components/hero/index'
import styles from 'styles/home.module.scss';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <h1>
                    Bienvenido a el  <a href="#">blog delluis</a>
                </h1>

                <Hero/>

            </main>


        </div>
    )
}
