import Head from 'next/head'
import Hero from '../components/hero/index'
import styles from 'styles/home.module.scss';
import FeaturedPost from "../components/featured-post/index";

export default function Home() {

    const DUMMY_POSTS = [
        {
            slug: 'this-is-my-first-slug',
            title: 'this is my first slug',
            image: 'this-is-my-first-slug.png',
            excerpt: 'this is an excerpt from my first slug',
            date: '2022-12-09',
        },
        {
            slug: 'this-is-my-second-slug',
            title: 'this is my second slug',
            image: 'this-is-my-second-slug.png',
            excerpt: 'this is an excerpt from my second slug',
            date: '2022-12-22',
        },
        {
            slug: 'this-is-my-third-slug',
            title: 'this is my third slug',
            image: 'this-is-my-third-slug.png',
            excerpt: 'this is an excerpt from my third slug',
            date: '2022-12-28',
        },
        {
            slug: 'this-is-my-fourth-slug',
            title: 'this is my fourth slug',
            image: 'this-is-my-fourth-slug.png',
            excerpt: 'this is an excerpt from my fourth slug',
            date: '2023-01-02',
        },

    ]


    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>


                <Hero/>
                <FeaturedPost posts={DUMMY_POSTS}/>

            </main>


        </div>
    )
}
