import Head from 'next/head'
import Hero from '../components/hero/index'
import styles from 'styles/home.module.scss';
import FeaturedPost from "../components/featured-post/index";
import {getFeaturedPosts} from "../lib/post-util";

export default function Home(props) {


    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>


                <Hero/>
                <FeaturedPost posts={props.posts}/>

            </main>


        </div>
    )
}

export function getStaticProps() {
    const featuredPosts = getFeaturedPosts()

    return {
        props: {
            posts: featuredPosts,
        },
        revalidate: 60,
    }
}
